# Generated by Django 5.0.14 on 2025-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergologia',
            fields=[
                ('ID_SHARE', models.AutoField(primary_key=True, serialize=False)),
                ('FOLIO', models.CharField(blank=True, max_length=100, null=True)),
                ('FECHA_FOLIO', models.DateField(blank=True, null=True)),
                ('MES_FOLIO', models.CharField(blank=True, max_length=100, null=True)),
                ('AÑO_FOLIO', models.IntegerField(blank=True, null=True)),
                ('DOCUMENTO', models.CharField(blank=True, max_length=100, null=True)),
                ('SEDE', models.CharField(blank=True, max_length=6, null=True)),
                ('ACTIVIDAD', models.CharField(blank=True, max_length=200, null=True)),
                ('CODIGO_DIGNOSTICO', models.CharField(blank=True, max_length=100, null=True)),
                ('DIAGNOSTICO', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_PROVOCACION_MEDICAMENTO', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_PROVOCACION_ALIMENTO', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_PRICK', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_PARCHE_ALIMENTOS_MEDICAMENTOS', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_ALIMENTOS_MENORES_A_2_AÑOS', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_PARCHE_BATERIA_ESTANDAR', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_CUTANEA_AEROALERGENOS', models.CharField(blank=True, max_length=200, null=True)),
                ('PRUEBA_CUTANEA_ALIMENTOS', models.CharField(blank=True, max_length=200, null=True)),
                ('TRATAMIENTO_FARMACOLOGICO', models.CharField(blank=True, max_length=200, null=True)),
                ('INMUNOTERAPIA', models.CharField(blank=True, max_length=200, null=True)),
                ('FECHA_ULTIMA_INMUNOTERAPIA', models.DateField(blank=True, null=True)),
                ('RESOLUCION_PACIENTE', models.CharField(blank=True, max_length=200, null=True)),
                ('OBSERVACIONES_GENERALES', models.CharField(blank=True, db_column='OBSERVACIONES_GENERALES_', max_length=1000, null=True)),
                ('CLASIFICACION', models.CharField(blank=True, max_length=200, null=True)),
                ('USUARIO_INVITADO', models.CharField(blank=True, max_length=200, null=True)),
                ('CREADO', models.DateField(blank=True, null=True)),
                ('CREADO_POR', models.CharField(blank=True, max_length=200, null=True)),
                ('MODIFICADO', models.DateField(blank=True, null=True)),
                ('MODIFICADO_POR', models.CharField(blank=True, max_length=200, null=True)),
                ('MEDICAMENTOS_INMUNOTERAPIA', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'SA_PacientesInmunoterapia_Alergologia',
                'permissions': [('ver_app_alergologia', 'Puede ver la aplicación de alergología'), ('editar_alergologia', 'Puede editar registros de alergología'), ('agregar_alergologia', 'Puede agregar registros de alergología')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inmunoterapia',
            fields=[
                ('IDSHARE', models.AutoField(primary_key=True, serialize=False)),
                ('EPS', models.CharField(blank=True, max_length=200, null=True)),
                ('SEDE', models.CharField(blank=True, max_length=6, null=True)),
                ('DOCUMENTO', models.CharField(blank=True, max_length=100, null=True)),
                ('NOMBRE_PACIENTE', models.CharField(blank=True, max_length=100, null=True)),
                ('EDAD', models.IntegerField(blank=True, null=True)),
                ('TELEFONO', models.CharField(blank=True, max_length=100, null=True)),
                ('HC_MEDICAMENTO', models.CharField(blank=True, max_length=10000, null=True)),
                ('FECHA_ULTIMA_VACUNA', models.DateTimeField(blank=True, null=True)),
                ('DOSIS', models.FloatField(blank=True, null=True)),
                ('NUMERO_DOSIS_APLICADA', models.IntegerField(blank=True, null=True)),
                ('ESCALA_VISUAL_ANALOGA_MEJORIA', models.CharField(blank=True, max_length=200, null=True)),
                ('REGISTRO_ADHERENCIA', models.CharField(blank=True, max_length=300, null=True)),
                ('NO_ADHERENCIA', models.CharField(blank=True, max_length=300, null=True)),
                ('OTROS', models.CharField(blank=True, max_length=1000, null=True)),
                ('MEDICO_TRATANTE', models.CharField(blank=True, max_length=200, null=True)),
                ('AUXILIAR_RESPONSABLE', models.CharField(blank=True, max_length=200, null=True)),
                ('FECHA_PROXIMA_CITA', models.DateTimeField(blank=True, null=True)),
                ('FINALIZACION_TRATAMIENTO', models.CharField(max_length=100)),
                ('CREADO', models.DateTimeField(blank=True, null=True)),
                ('CREADO_POR', models.CharField(blank=True, max_length=200, null=True)),
                ('MODIFICADO', models.DateTimeField(blank=True, null=True)),
                ('MODIFICADO_POR', models.CharField(blank=True, max_length=200, null=True)),
                ('FECHA_ULTIMO_FOLIO', models.DateTimeField(blank=True, null=True)),
                ('ID_SQL', models.IntegerField(blank=True, null=True)),
                ('CLASIFICACION_TRATAMIENTO', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'SA_PacientesInmunoterapia',
                'permissions': [('ver_app_inmunoterapia', 'Puede ver la aplicación de inmunoterapia'), ('editar_inmunoterapia', 'Puede editar registros de inmunoterapia'), ('agregar_inmunoterapia', 'Puede agregar registros de inmunoterapia')],
                'managed': False,
            },
        ),
    ]
